Repository Team-B1ND/dodam-teacher-android-v6, pull requests merged in 2024-04, with the labels that each got.

#58 Code Check
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/home/screen/HomeScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/home/vm/HomeViewModel.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/screen/OutScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/vm/OutViewModel.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/vm/MainViewModel.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/out/screen/CurrentOutScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/out/vm/CurrentOutViewModel.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/datasource/AuthRemoteDataSourceImpl.kt
Labels: REFACTORING ♻️

#60 Version Up
  buildSrc/src/main/java/ProjectProperties.kt
Labels: RELEASE 🚀

#62 Version Code Up
  buildSrc/src/main/java/ProjectProperties.kt
Labels: RELEASE 🚀

#65 심사 승인 버그 수정 및 자잘하게 수정
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/screen/OutScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/night_study/current/screen/CurrentNightStudyScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/night_study/screen/NightStudyScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/out/screen/CurrentOutScreen.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/NightStudyResponseMapper.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/OutResponseMapper.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/response/night_study/NightStudyResponse.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/response/out/OutResponse.kt
Labels: BUG 🐛

#66 심사 승인 버그 수정 및 자잘하게 수정
  buildSrc/src/main/java/ProjectProperties.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/screen/OutScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/night_study/current/screen/CurrentNightStudyScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/night_study/screen/NightStudyScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/out/screen/CurrentOutScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/point/vm/PointViewModel.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/NightStudyResponseMapper.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/OutResponseMapper.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/response/night_study/NightStudyResponse.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/response/out/OutResponse.kt
Labels: BUG 🐛

#70 LocalDateTime 및 심자, 외출, 외박 버그 수정
  buildSrc/src/main/java/ProjectProperties.kt
  data/src/main/java/kr/hs/dgsw/smartschool/data/utils/LocalDateUtils.kt
  domain/src/main/java/kr/hs/dgsw/smartschool/domain/repository/StudentRepository.kt
  local/src/main/java/kr/hs/dgsw/smartschool/local/mapper/MemberEntityMapper.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/screen/OutScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/vm/OutViewModel.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/out/vm/CurrentOutViewModel.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/AuthResponseMapper.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/OutResponseMapper.kt
Labels: BUG 🐛

#69 LocalDateTime 및 심자, 외출, 외박 버그 수정
  buildSrc/src/main/java/ProjectProperties.kt
  data/src/main/java/kr/hs/dgsw/smartschool/data/utils/LocalDateUtils.kt
  domain/src/main/java/kr/hs/dgsw/smartschool/domain/repository/StudentRepository.kt
  local/src/main/java/kr/hs/dgsw/smartschool/local/mapper/MemberEntityMapper.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/screen/OutScreen.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/main/out/vm/OutViewModel.kt
  presentation/src/main/java/kr/hs/dgsw/smartschool/dodamdodam_teacher/features/out/vm/CurrentOutViewModel.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/AuthResponseMapper.kt
  remote/src/main/java/kr/hs/dgsw/smartschool/remote/mapper/OutResponseMapper.kt
Labels: BUG 🐛
